api_platform:
  resource: 'App\Entity\Admins'

  collectionOperations:
    - path: "/admins"
      controller: 'App\Controller\AdminsController::createAdmins'
      defaults:
        _api_receive: false

  itemOperations: ~
